"""Shared pytest fixtures for the backend test suite."""
from __future__ import annotations

from pathlib import Path
from typing import Iterable

import openpyxl
import pytest


REALPAGE_METADATA_ROWS = (
    ("Rent Roll with Lease Charges",),
    ("Talisman Golden Sutherland",),
    ("As of: 04/14/2026",),
    (),
    ("Report generated by: Manager",),
)

REALPAGE_HEADER = (
    "Unit", "Floor Plan", "SqFt", "Resident", "Status",
    "Market Rent", "Lease Rent", "Move In", "Lease End",
)


def _write_row(ws, row_idx: int, values: Iterable) -> None:
    for col_idx, val in enumerate(values, start=1):
        ws.cell(row=row_idx, column=col_idx, value=val)


def _build_realpage_with_future_residents_workbook(path: Path) -> None:
    """Synthesize a RealPage-shaped workbook matching the production 60 11th St file.

    Layout:
      - 5 metadata rows
      - 1 header row
      - "Current/Notice/Vacant Residents" banner
      - 320 unit rows (synthetic, no PII)
      - "Future Residents/Applicants" banner
      - 10 pre-lease rows whose unit_numbers duplicate the first 10 Current units
      - "Summary Groups" banner
      - 7 summary-section rows
    """
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Rent Roll"

    row_idx = 1
    for meta in REALPAGE_METADATA_ROWS:
        _write_row(ws, row_idx, meta)
        row_idx += 1
    _write_row(ws, row_idx, REALPAGE_HEADER)
    row_idx += 1

    _write_row(ws, row_idx, ["Current/Notice/Vacant Residents"])
    row_idx += 1

    unit_numbers: list[str] = []
    for i in range(320):
        floor = (i // 20) + 1
        apt = (i % 20) + 1
        unit_num = f"{floor:02d}{apt:02d}"
        unit_numbers.append(unit_num)
        sqft = 750 + (i % 4) * 80
        market_rent = 1400 + (i % 10) * 25
        in_place = market_rent - (i % 5) * 20
        status = "Occupied No Notice" if i % 7 != 0 else "Vacant Unrented Ready"
        resident = f"Resident {i + 1:04d}" if status.startswith("Occupied") else None
        _write_row(ws, row_idx, [
            unit_num, f"A{(i % 4) + 1}", sqft, resident, status,
            market_rent, in_place if status.startswith("Occupied") else None,
            "2024-06-01" if status.startswith("Occupied") else None,
            "2026-06-01" if status.startswith("Occupied") else None,
        ])
        row_idx += 1

    _write_row(ws, row_idx, ["Future Residents/Applicants"])
    row_idx += 1

    # 10 pre-leases that duplicate unit_numbers from the Current section.
    for i in range(10):
        _write_row(ws, row_idx, [
            unit_numbers[i], f"A{(i % 4) + 1}", 800,
            f"Incoming {i + 1}", "Applicant",
            1500, 1450, "2026-05-01", "2027-05-01",
        ])
        row_idx += 1

    _write_row(ws, row_idx, ["Summary Groups"])
    row_idx += 1
    # 7 rows under the summary banner. Each carries a numeric value so it is
    # treated as a data row under SUMMARY (not itself classified as a banner).
    for label, rent in [
        ("Non Rev Total", 0),
        ("Vacant Total", 50000),
        ("Occupied Total", 400000),
        ("Charge Total", 450000),
        ("Market Rent Total", 480000),
        ("Loss to Lease", -30000),
        ("Net Charges", 450000),
    ]:
        _write_row(ws, row_idx, [label, "", "", "", "", rent, None, "", ""])
        row_idx += 1

    wb.save(str(path))
    wb.close()


@pytest.fixture(scope="session")
def realpage_with_future_residents_xlsx(tmp_path_factory) -> Path:
    """Build the synthetic RealPage fixture once per session in a temp directory.

    We generate on-demand instead of checking in the .xlsx binary so diffs
    stay reviewable and the fixture layout stays in sync with this code.
    """
    fixture_dir = tmp_path_factory.mktemp("rent_roll_fixtures")
    path = fixture_dir / "realpage_with_future_residents.xlsx"
    _build_realpage_with_future_residents_workbook(path)
    return path
