"""Tests for rent_roll_normalizer.

Covers the eight assertions from the task spec:
  1. "Current/Notice/Vacant Residents" banner row is filtered as junk
     with a reason.
  2. Total/Subtotal rows are filtered.
  3. All real units parse when fed a clean table.
  4. Header detection finds the correct row even when preceded by 5+
     metadata rows.
  5. Column aliasing works — `"Apt #"` instead of `"Unit"` still maps.
  6. VARCHAR overflow doesn't crash — truncated with a warning.
  7. Unmapped columns appear in `unmapped_columns`, not silently dropped.
  8. Missing/malformed dates coerce to None, don't crash.
  9. Currency with `$`, `,`, `()` parses correctly.
"""
from datetime import datetime
from pathlib import Path

import openpyxl
import pytest

from app.services.extraction.rent_roll_normalizer import (
    COLUMN_MAX_LENGTHS,
    FutureLease,
    NormalizationResult,
    RentRollSection,
    classify_banner,
    coerce_currency,
    coerce_date,
    derive_is_occupied,
    derive_status_from_dates,
    detect_header_row,
    is_junk_row,
    normalize_rows,
    normalize_units,
)


# ─── Synthetic fixtures ──────────────────────────────────────────────────────

REALPAGE_METADATA_ROWS = [
    ["Rent Roll with Lease Charges", "", "", "", "", "", ""],
    ["Talisman Golden Sutherland", "", "", "", "", "", ""],
    ["As of: 04/14/2026", "", "", "", "", "", ""],
    ["", "", "", "", "", "", ""],
    ["Report generated by: Manager", "", "", "", "", "", ""],
]

REALPAGE_HEADER = [
    "Unit", "Floor Plan", "SqFt", "Resident", "Status",
    "Market Rent", "Lease Rent", "Move In", "Lease End",
]


def realpage_table(units: list[list]) -> list[list]:
    """Return a full RealPage-shaped table: 5 metadata rows, then header, then units."""
    return [*REALPAGE_METADATA_ROWS, REALPAGE_HEADER, *units]


# ─── 1. Banner-row filtering ─────────────────────────────────────────────────

def test_current_notice_vacant_banner_is_junk():
    banner = {
        "unit_number": "Current/Notice/Vacant Residents",
        "resident_name": None,
        "market_rent": None,
        "in_place_rent": None,
    }
    junk, reason = is_junk_row(banner)
    assert junk is True
    assert "section header" in reason
    assert "current/notice/vacant" in reason.lower()


def test_banner_row_kept_out_of_units_list_with_reason():
    table = realpage_table([
        ["Current/Notice/Vacant Residents", "", "", "", "", "", "", "", ""],
        ["101", "A1", 800, "Jane Doe", "Occupied", 1200, 1150, "2025-01-01", "2026-01-01"],
    ])
    result = normalize_rows(table)
    assert result.header_row_index == 5
    assert len(result.units) == 1
    assert result.units[0]["unit_number"] == "101"
    assert len(result.skipped_rows) == 1
    assert "section header" in result.skipped_rows[0]["reason"]


# ─── 2. Total / subtotal rows ───────────────────────────────────────────────

def test_total_and_subtotal_rows_are_filtered():
    table = realpage_table([
        ["101", "A1", 800, "Jane", "Occupied", 1200, 1150, "2025-01-01", "2026-01-01"],
        ["Subtotal", "", "", "", "", 1200, 1150, "", ""],
        ["102", "A1", 800, "John", "Occupied", 1200, 1170, "2025-02-01", "2026-02-01"],
        ["Total", "", "", "", "", 2400, 2320, "", ""],
    ])
    result = normalize_rows(table)
    assert len(result.units) == 2
    reasons = [r["reason"] for r in result.skipped_rows]
    assert any("section header" in r for r in reasons)
    assert sum("subtotal" in r.lower() or "total" in r.lower() for r in reasons) >= 2


# ─── 3. Clean table: everything parses ──────────────────────────────────────

def test_clean_table_all_units_parse():
    table = realpage_table([
        ["101", "A1", 800, "Jane", "Occupied", 1200, 1150, "2025-01-01", "2026-01-01"],
        ["102", "A1", 800, "John", "Occupied", 1200, 1170, "2025-02-01", "2026-02-01"],
        ["103", "A2", 900, None, "Vacant", 1300, None, None, None],
    ])
    result = normalize_rows(table)
    assert result.error is None
    assert len(result.units) == 3
    assert result.units[0]["unit_number"] == "101"
    assert result.units[0]["sqft"] == 800
    assert result.units[0]["market_rent"] == 1200
    assert result.units[0]["in_place_rent"] == 1150
    assert result.units[0]["is_occupied"] is True
    assert result.units[2]["is_occupied"] is False
    assert result.units[2]["resident_name"] is None


# ─── 4. Header detection under metadata rows ────────────────────────────────

def test_header_detection_skips_metadata_rows():
    table = realpage_table([
        ["101", "A1", 800, "Jane", "Occupied", 1200, 1150, "2025-01-01", "2026-01-01"],
    ])
    result = normalize_rows(table)
    assert result.header_row_index == 5
    assert len(result.units) == 1


def test_header_detection_returns_minus_one_when_no_candidate():
    table = [
        ["Foo", "Bar", "Baz"],
        ["1", "2", "3"],
        ["4", "5", "6"],
    ]
    idx = detect_header_row(table)
    assert idx == -1


def test_normalize_returns_clear_error_when_header_not_detected():
    table = [["Foo", "Bar"], ["1", "2"]]
    result = normalize_rows(table)
    assert result.header_row_index == -1
    assert result.error is not None
    assert "header" in result.error.lower()
    assert result.units == []


# ─── 5. Column aliasing (Apt # instead of Unit) ──────────────────────────────

def test_apt_hash_alias_maps_to_unit_number():
    table = [
        ["Yardi Export", "", "", "", "", "", ""],
        ["", "", "", "", "", "", ""],
        ["Apt #", "Unit Type", "Size", "Resident Name", "Lease Status",
         "Market Rent", "Actual Rent"],
        ["A-101", "2BR", 1100, "Alice", "Occupied", 1800, 1750],
        ["A-102", "2BR", 1100, "Bob", "Occupied", 1800, 1780],
    ]
    result = normalize_rows(table)
    assert result.error is None
    assert result.column_mapping.get("unit_number") == "Apt #"
    assert result.column_mapping.get("unit_type") == "Unit Type"
    assert result.column_mapping.get("market_rent") == "Market Rent"
    assert len(result.units) == 2


# ─── 6. Truncation doesn't crash (surfaces warning) ──────────────────────────

def test_oversize_strings_truncated_with_warning():
    long_unit = "X" * 120  # > 50
    long_plan = "P" * 80   # > 50
    long_name = "N" * 300  # > 255
    table = realpage_table([
        [long_unit, long_plan, 800, long_name, "Occupied", 1200, 1150,
         "2025-01-01", "2026-01-01"],
    ])
    result = normalize_rows(table)
    assert len(result.units) == 1
    assert len(result.units[0]["unit_number"]) == COLUMN_MAX_LENGTHS["unit_number"]
    assert len(result.units[0]["unit_type"]) == COLUMN_MAX_LENGTHS["unit_type"]
    assert len(result.units[0]["resident_name"]) == COLUMN_MAX_LENGTHS["resident_name"]
    assert any("truncated" in w for w in result.warnings)


# ─── 7. Unmapped columns surfaced ────────────────────────────────────────────

def test_unknown_columns_land_in_unmapped_list():
    table = [
        ["Unit", "Sq Ft", "Resident", "Market Rent", "Lease Rent",
         "Lease Start", "Lease End", "Some Weird PMS Column", "Concessions"],
        ["101", 800, "Jane", 1200, 1150, "2025-01-01", "2026-01-01", "foo", 50],
    ]
    result = normalize_rows(table)
    assert "Some Weird PMS Column" in result.unmapped_columns
    assert "Concessions" in result.unmapped_columns
    assert result.column_mapping.get("unit_number") == "Unit"


# ─── 8. Date coercion is defensive ───────────────────────────────────────────

@pytest.mark.parametrize("bad_value", ["", "N/A", "not a date", None, "  "])
def test_malformed_dates_coerce_to_none(bad_value):
    assert coerce_date(bad_value) is None


def test_excel_serial_date_parses():
    # 45000 ≈ 2023-03-15 in Excel's 1900-epoch serial.
    parsed = coerce_date(45000)
    assert parsed is not None
    assert 2023 <= parsed.year <= 2024


@pytest.mark.parametrize("fmt_value,expected", [
    ("2025-01-15", datetime(2025, 1, 15)),
    ("01/15/2025", datetime(2025, 1, 15)),
    ("1/5/25", datetime(2025, 1, 5)),
])
def test_common_date_formats_parse(fmt_value, expected):
    assert coerce_date(fmt_value) == expected


def test_malformed_date_in_row_does_not_crash_pipeline():
    table = realpage_table([
        ["101", "A1", 800, "Jane", "Occupied", 1200, 1150, "not a date", "garbage"],
    ])
    result = normalize_rows(table)
    assert len(result.units) == 1
    assert result.units[0]["lease_start"] is None
    assert result.units[0]["lease_end"] is None


# ─── 9. Currency coercion ────────────────────────────────────────────────────

@pytest.mark.parametrize("raw,expected", [
    ("$1,200.00", 1200.00),
    ("1,200", 1200.0),
    ("($50.00)", -50.0),
    ("1200", 1200.0),
    (1200, 1200.0),
    (1200.5, 1200.5),
    ("", None),
    ("-", None),
    ("N/A", None),
    ("  $  2,345.67 ", 2345.67),
])
def test_currency_parsing(raw, expected):
    result = coerce_currency(raw)
    if expected is None:
        assert result is None
    else:
        assert result == pytest.approx(expected)


# ─── Occupancy derivation ────────────────────────────────────────────────────

@pytest.mark.parametrize("status,expected", [
    ("Occupied", True),
    ("Occupied No Notice", True),
    ("Current", True),
    ("Notice", True),
    ("Vacant", False),
    ("Vacant Unrented Ready", False),
    ("Model", False),
    ("Down", False),
    ("Admin", False),
    ("", None),
    (None, None),
    ("Something Weird", None),
])
def test_derive_is_occupied(status, expected):
    assert derive_is_occupied(status) is expected


# ─── normalize_units (legacy wrapper) ────────────────────────────────────────

def test_normalize_units_filters_banner_row_from_legacy_extractor_output():
    # The legacy openpyxl parser returns a list of pre-mapped dicts. Verify
    # that the "Current/Notice/Vacant Residents" banner is still filtered.
    units = [
        {"unit_number": "Current/Notice/Vacant Residents",
         "resident_name": None, "market_rent": None, "in_place_rent": None},
        {"unit_number": "101", "unit_type": "A1", "sqft": 800,
         "resident_name": "Jane Doe", "status": "Occupied",
         "market_rent": 1200, "in_place_rent": 1150,
         "lease_start": "2025-01-01", "lease_end": "2026-01-01"},
        {"unit_number": "Total", "resident_name": None,
         "market_rent": 1200, "in_place_rent": 1150},
    ]
    result = normalize_units(units, {"unit_number": "Unit"})
    assert len(result.units) == 1
    assert result.units[0]["unit_number"] == "101"
    assert len(result.skipped_rows) == 2


def test_normalize_units_truncates_oversize_unit_number():
    """Regression: the production StringDataRightTruncation error came from
    shoving 'Current/Notice/Vacant Residents' (30 chars) into VARCHAR(20).
    After the migration -> VARCHAR(50), a short banner like this still gets
    filtered as junk. But if someone constructs a real unit_number > 50,
    we truncate-with-warning rather than crash.
    """
    units = [
        {"unit_number": "A" * 120, "unit_type": "B2",
         "resident_name": "Jane Doe", "status": "Occupied",
         "market_rent": 1500, "in_place_rent": 1450},
    ]
    result = normalize_units(units)
    assert len(result.units) == 1
    assert len(result.units[0]["unit_number"]) == 50
    assert any("truncated" in w for w in result.warnings)


# ─── Sanity: NormalizationResult shape ───────────────────────────────────────

def test_normalization_result_defaults():
    r = NormalizationResult()
    assert r.units == []
    assert r.skipped_rows == []
    assert r.unmapped_columns == []
    assert r.column_mapping == {}
    assert r.warnings == []
    assert r.header_row_index == -1
    assert r.total_rows_scanned == 0
    assert r.error is None
    assert r.future_leases == []
    assert r.sections_detected == {}


# ─── Section-aware filtering (v2) ────────────────────────────────────────────

def _banner_row(text: str) -> list:
    """Build a 9-wide row with only cell 0 populated — matches REALPAGE_HEADER width."""
    return [text, "", "", "", "", "", "", "", ""]


def test_classify_banner_basic():
    assert classify_banner("Current/Notice/Vacant Residents") == RentRollSection.CURRENT_NOTICE_VACANT
    assert classify_banner("Future Residents/Applicants") == RentRollSection.FUTURE_APPLICANTS
    assert classify_banner("Summary Groups") == RentRollSection.SUMMARY
    assert classify_banner("Total Vacant Units") == RentRollSection.SUMMARY
    assert classify_banner("Grand Total") == RentRollSection.SUMMARY
    assert classify_banner("Summary of Charges by Charge Code") == RentRollSection.SUMMARY
    # Non-banner strings
    assert classify_banner("101") is None
    assert classify_banner("") is None
    assert classify_banner(None) is None
    assert classify_banner(1200) is None
    # Resident names that contain banner-adjacent words must NOT classify.
    assert classify_banner("Currentin Jones") is None  # "current" but no notice/vacant/resident/slash
    assert classify_banner("Summer Applegate") is None  # "applegate" != "applicant"


def test_section_tagging_splits_current_and_future():
    """Spec test 1: section tagging separates Current vs Future into distinct buckets."""
    table = realpage_table([
        _banner_row("Current/Notice/Vacant Residents"),
        ["101", "A1", 800, "Jane", "Occupied", 1200, 1150, "2025-01-01", "2026-01-01"],
        ["102", "A1", 800, "John", "Occupied", 1200, 1170, "2025-02-01", "2026-02-01"],
        ["103", "A2", 900, None, "Vacant", 1300, None, None, None],
        _banner_row("Future Residents/Applicants"),
        ["201", "B1", 1000, "Alice Incoming", "Applicant", 1500, 1400, "2025-06-01", "2026-06-01"],
        ["202", "B1", 1000, "Bob Pending", "Applicant", 1500, 1400, "2025-07-01", "2026-07-01"],
    ])
    result = normalize_rows(table)
    assert len(result.units) == 3
    assert [u["unit_number"] for u in result.units] == ["101", "102", "103"]
    assert len(result.future_leases) == 2
    assert [fl.unit_number for fl in result.future_leases] == ["201", "202"]
    assert result.sections_detected == {
        "current_notice_vacant": 3,
        "future_applicants": 2,
    }


def test_future_unit_numbers_duplicating_current_are_not_counted():
    """Spec test 2: duplicate unit numbers in Future section do NOT inflate the unit count."""
    table = realpage_table([
        _banner_row("Current/Notice/Vacant Residents"),
        ["101", "A1", 800, "Jane", "Occupied", 1200, 1150, "2025-01-01", "2026-01-01"],
        ["102", "A1", 800, "John", "Occupied", 1200, 1170, "2025-02-01", "2026-02-01"],
        ["103", "A2", 900, None, "Vacant", 1300, None, None, None],
        _banner_row("Future Residents/Applicants"),
        # These duplicate unit_numbers from Current — pre-leases on existing units.
        ["102", "A1", 800, "New Incoming Tenant", "Applicant", 1250, 1250, "2025-06-01", "2026-06-01"],
        ["103", "A2", 900, "Another Incoming", "Applicant", 1350, 1350, "2025-07-01", "2026-07-01"],
    ])
    result = normalize_rows(table)
    assert [u["unit_number"] for u in result.units] == ["101", "102", "103"]
    assert len(result.units) == 3
    assert len(result.future_leases) == 2


def test_summary_sections_are_filtered():
    """Spec test 3: Summary Groups / Total Non Rev / Summary of Charges all skip."""
    table = realpage_table([
        _banner_row("Current/Notice/Vacant Residents"),
        ["101", "A1", 800, "Jane", "Occupied", 1200, 1150, "2025-01-01", "2026-01-01"],
        _banner_row("Summary Groups"),
        ["Summary Group Alpha", "", "", "", "", 1200, 1150, "", ""],
        _banner_row("Total Non Rev Units"),
        ["Non Rev Row", "", "", "", "", "", "", "", ""],
        _banner_row("Summary of Charges by Charge Code"),
        ["Rent", "", "", "", "", 1150, "", "", ""],
    ])
    result = normalize_rows(table)
    assert len(result.units) == 1
    assert result.units[0]["unit_number"] == "101"
    # Each of the three summary banners should appear in skipped_rows as a banner.
    banner_reasons = [
        s["reason"] for s in result.skipped_rows
        if "section header banner" in s["reason"]
    ]
    assert sum("summary" in r for r in banner_reasons) >= 3
    # Rows UNDER summary banners are marked summary_section.
    assert any(s["reason"] == "summary_section" for s in result.skipped_rows)
    assert result.sections_detected.get("summary", 0) >= 3


def test_future_lease_payload_preserved():
    """Spec test 4: future_leases captures resident_name, rents, and lease dates."""
    # Use a header that has explicit Lease Start and Lease End columns to exercise
    # the lease_start capture path.
    table = [
        ["Rent Roll", "", "", "", "", "", "", "", ""],
        ["", "", "", "", "", "", "", "", ""],
        ["Unit", "Floor Plan", "SqFt", "Resident", "Status",
         "Market Rent", "Lease Rent", "Lease Start", "Lease End"],
        ["Current/Notice/Vacant Residents", "", "", "", "", "", "", "", ""],
        ["101", "A1", 800, "Jane", "Occupied", 1200, 1150, "2025-01-01", "2026-01-01"],
        ["Future Residents/Applicants", "", "", "", "", "", "", "", ""],
        ["201", "B1", 1000, "Alice Incoming", "Applicant", 1500, 1400, "2025-06-15", "2026-06-15"],
        ["202", "B1", 1000, "Bob Pending", "Applicant", 1500, 1400, "2025-07-20", "2026-07-20"],
    ]
    result = normalize_rows(table)
    assert len(result.future_leases) == 2
    first = result.future_leases[0]
    assert first.unit_number == "201"
    assert first.resident_name == "Alice Incoming"
    assert first.lease_start == datetime(2025, 6, 15)
    assert first.lease_end == datetime(2026, 6, 15)
    assert first.market_rent == 1500.0
    assert isinstance(first.raw_row, dict)
    # Second lease too.
    assert result.future_leases[1].resident_name == "Bob Pending"
    assert result.future_leases[1].lease_start == datetime(2025, 7, 20)


def test_resident_name_containing_banner_word_is_not_filtered():
    """Spec test 5: `Currentin Jones` / `Summer Applegate` must pass through as real units."""
    table = realpage_table([
        _banner_row("Current/Notice/Vacant Residents"),
        ["101", "A1", 800, "Currentin Jones", "Occupied", 1200, 1150,
         "2025-01-01", "2026-01-01"],
        ["102", "A1", 800, "Summer Applegate", "Occupied", 1200, 1170,
         "2025-02-01", "2026-02-01"],
    ])
    result = normalize_rows(table)
    assert len(result.units) == 2
    assert result.units[0]["resident_name"] == "Currentin Jones"
    assert result.units[1]["resident_name"] == "Summer Applegate"
    # Neither should appear in skipped_rows.
    skipped_residents = [
        str(s["raw"].get("resident_name", "")) for s in result.skipped_rows
    ]
    assert "Currentin Jones" not in skipped_residents
    assert "Summer Applegate" not in skipped_residents


def test_normalize_units_preserves_future_leases():
    """normalize_units (legacy wrapper) also tags sections when banners come through as dicts."""
    units = [
        {"unit_number": "Current/Notice/Vacant Residents",
         "resident_name": None, "market_rent": None, "in_place_rent": None,
         "sqft": None},
        {"unit_number": "101", "unit_type": "A1", "sqft": 800,
         "resident_name": "Jane Doe", "status": "Occupied",
         "market_rent": 1200, "in_place_rent": 1150,
         "lease_start": "2025-01-01", "lease_end": "2026-01-01"},
        {"unit_number": "Future Residents/Applicants",
         "resident_name": None, "market_rent": None, "in_place_rent": None,
         "sqft": None},
        {"unit_number": "202", "unit_type": "B1", "sqft": 1000,
         "resident_name": "Alice Incoming", "status": "Applicant",
         "market_rent": 1500, "in_place_rent": 1400,
         "lease_start": "2025-06-01", "lease_end": "2026-06-01"},
    ]
    result = normalize_units(units, {"unit_number": "Unit"})
    assert len(result.units) == 1
    assert result.units[0]["unit_number"] == "101"
    assert len(result.future_leases) == 1
    assert result.future_leases[0].unit_number == "202"
    assert result.future_leases[0].resident_name == "Alice Incoming"
    assert result.sections_detected.get("current_notice_vacant") == 1
    assert result.sections_detected.get("future_applicants") == 1


# ─── End-to-end: synthetic RealPage fixture with 320 units + 10 pre-leases ───

def test_realpage_with_future_residents_end_to_end(realpage_with_future_residents_xlsx: Path):
    """The reference failing case: 320-unit property with 10 future pre-leases.

    Before the v2 fix the normalizer returned 330 units; after the fix it
    returns exactly 320 units plus 10 future_leases.
    """
    wb = openpyxl.load_workbook(str(realpage_with_future_residents_xlsx), data_only=True)
    ws = wb.worksheets[0]
    rows = [list(row) for row in ws.iter_rows(values_only=True)]
    wb.close()

    result = normalize_rows(rows)
    assert result.error is None
    assert len(result.units) == 320
    assert len(result.future_leases) == 10
    assert result.sections_detected.get("current_notice_vacant") == 320
    assert result.sections_detected.get("future_applicants") == 10
    assert result.sections_detected.get("summary", 0) >= 7
    # Future-lease unit_numbers duplicate the first 10 Current units.
    current_first_10 = [u["unit_number"] for u in result.units[:10]]
    future_unit_numbers = [fl.unit_number for fl in result.future_leases]
    assert future_unit_numbers == current_first_10


# ─── Regressions for the 332-unit RealPage overcount bug ─────────────────────

def test_future_residents_banner_detected_with_zero_in_place_rent():
    """The extractor emits `in_place_rent=0` on every dict including banners.

    Before the fix, `_is_banner_shaped_dict` rejected such rows (since 0 is
    not blank), so the section state never advanced into FUTURE_APPLICANTS
    and pre-lease rows leaked into result.units.
    """
    units = [
        {"unit_number": "101", "unit_type": "A1", "sqft": 800,
         "resident_name": "Jane Doe", "status": "Occupied",
         "market_rent": 1200, "in_place_rent": 1150},
        # Banner row as emitted by the legacy extractor: text in unit_number,
        # in_place_rent defaulted to 0, everything else None.
        {"unit_number": "Future Residents/Applicants",
         "unit_type": None, "sqft": None, "resident_name": None,
         "status": None, "market_rent": None, "in_place_rent": 0,
         "charge_details": {}},
        {"unit_number": "202", "unit_type": "B1", "sqft": 1000,
         "resident_name": "Alice Incoming", "status": None,
         "market_rent": 1500, "in_place_rent": 0,
         "lease_start": "2025-06-01", "lease_end": "2026-06-01"},
    ]
    result = normalize_units(units, {"unit_number": "Unit"})
    assert len(result.units) == 1
    assert result.units[0]["unit_number"] == "101"
    assert len(result.future_leases) == 1
    assert result.future_leases[0].unit_number == "202"
    assert result.sections_detected.get("future_applicants") == 1


def test_charge_code_short_tokens_rejected():
    """The RealPage Summary of Charges block emits rows whose col-A value is
    a short lowercase token (aprk, atra, mtm, ...). is_junk_row must reject
    all of them — `emp` and `Total` were already caught via substring match
    with `employee` / `total`, but the others slipped through.
    """
    leak_candidates = [
        "aprk", "atra", "arnt", "astg", "rrins", "con", "mtm", "prnt",
    ]
    for code in leak_candidates:
        unit = {
            "unit_number": code,
            "unit_type": None,
            "sqft": None,
            "resident_name": None,
            "market_rent": None,
            "in_place_rent": 1234.56,
        }
        junk, reason = is_junk_row(unit)
        assert junk is True, f"{code!r} slipped past is_junk_row"
        assert "charge_code" in reason or "section header" in reason

    # Existing rejections continue to work.
    for code in ["emp", "Total"]:
        unit = {
            "unit_number": code, "unit_type": None, "sqft": None,
            "resident_name": None, "market_rent": None, "in_place_rent": 0,
        }
        junk, reason = is_junk_row(unit)
        assert junk is True, f"{code!r} no longer rejected"

    # A legitimate short unit number (has digits or uppercase) must still pass.
    real_unit = {
        "unit_number": "A-2",
        "unit_type": "A1",
        "sqft": 800,
        "resident_name": "Jane Doe",
        "market_rent": 1200,
        "in_place_rent": 1150,
    }
    junk, reason = is_junk_row(real_unit)
    assert junk is False, f"real unit rejected: {reason}"


def test_status_assignment_from_move_out():
    """With no Status column, occupancy derives from Move Out / Lease End."""
    past = datetime(2025, 1, 1)
    future = datetime(2099, 1, 1)

    # Past Move Out → vacant.
    label, occ = derive_status_from_dates(past, future, "Former Tenant")
    assert occ is False
    assert label == "vacant"

    # Future Move Out → notice, still occupied.
    label, occ = derive_status_from_dates(future, future, "Jane Doe")
    assert occ is True
    assert label == "notice"

    # No Move Out, active lease + resident → current.
    label, occ = derive_status_from_dates(None, future, "Jane Doe")
    assert occ is True
    assert label == "current"

    # No lease, no Move Out, no resident → vacant.
    label, occ = derive_status_from_dates(None, None, None)
    assert occ is False
    assert label == "vacant"


def test_status_derived_through_normalize_units():
    """End-to-end: the derivation flows through normalize_units + _coerce_unit."""
    units = [
        # Occupied: resident, lease end in future, no move out, no status.
        {"unit_number": "101", "unit_type": "A1", "sqft": 800,
         "resident_name": "Jane Doe", "status": None,
         "move_out_date": None, "lease_end": datetime(2099, 1, 1),
         "market_rent": 1200, "in_place_rent": 1150, "is_occupied": None},
        # Vacant: resident moved out in the past.
        {"unit_number": "102", "unit_type": "A1", "sqft": 800,
         "resident_name": "Former Tenant", "status": None,
         "move_out_date": datetime(2025, 1, 1),
         "lease_end": datetime(2025, 1, 1),
         "market_rent": 1200, "in_place_rent": 0, "is_occupied": None},
        # Truly empty unit: no resident, no lease, no move out.
        {"unit_number": "103", "unit_type": "A2", "sqft": 900,
         "resident_name": None, "status": None,
         "move_out_date": None, "lease_end": None,
         "market_rent": 1300, "in_place_rent": 0, "is_occupied": None},
    ]
    result = normalize_units(units, {"unit_number": "Unit"})
    assert len(result.units) == 3
    by_num = {u["unit_number"]: u for u in result.units}
    assert by_num["101"]["is_occupied"] is True
    assert by_num["101"]["status"] == "current"
    assert by_num["102"]["is_occupied"] is False
    assert by_num["102"]["status"] == "vacant"
    assert by_num["103"]["is_occupied"] is False
    assert by_num["103"]["status"] == "vacant"


def test_realpage_summary_groups_parser():
    """The Summary Groups block at the foot of a RealPage sheet should
    surface as extraction["realpage_summary"]."""
    from openpyxl import Workbook
    from app.services.excel_extraction_service import _parse_realpage_summary_groups

    wb = Workbook()
    ws = wb.active
    # Headers
    ws.append(["Summary Groups", "Square Footage", "Market Rent",
               "Lease Charges", "# Units", "% Occupied"])
    ws.append(["Current/Notice/Vacant Residents", 303721, 863176, 819968.50, 320, 95.62])
    ws.append(["Future Residents/Applicants", 9243, 26422, 0.00, 10, None])
    ws.append(["Occupied Units", 288796, 821104, None, 306, 95.62])
    ws.append(["Total Non Rev Units", 1921, 5662, None, 2, None])
    ws.append(["Total Vacant Units", 13004, 36410, None, 12, None])
    ws.append(["Totals:", 303721, 863176, 819968.50, 320, 100.00])

    summary = _parse_realpage_summary_groups(ws)
    assert summary is not None
    assert summary["total_units"] == 320
    assert summary["occupied_units"] == 306
    assert summary["vacant_units"] == 12
    assert summary["non_rev_units"] == 2
    assert summary["future_leases"] == 10
    assert summary["total_sqft"] == 303721
    assert abs(summary["physical_occupancy_pct"] - 95.62) < 0.01


# ─── Sixty 11th surgical follow-up regressions ───────────────────────────────


def test_future_residents_banner_not_ingested_as_unit():
    """Regression for Sixty 11th: banner row with unit_number literal
    'Future Residents/Applicants' must never appear in result.units.
    """
    units = [
        {"unit_number": "101", "unit_type": "A1", "sqft": 800,
         "resident_name": "Jane Doe", "status": "Occupied",
         "market_rent": 1200, "in_place_rent": 1150},
        {"unit_number": "Future Residents/Applicants",
         "unit_type": None, "sqft": None, "resident_name": None,
         "status": None, "market_rent": None, "in_place_rent": 0,
         "charge_details": {}},
    ]
    result = normalize_units(units, {"unit_number": "Unit"})
    unit_numbers = [u["unit_number"] for u in result.units]
    assert "Future Residents/Applicants" not in unit_numbers


def test_future_residents_sixty_11th_ten_preleases_routed_to_future_leases():
    """Regression for Sixty 11th: the 10 pre-lease rows under the Future
    Residents banner (unit numbers 0614, 0711, 0907, 1010, 1113, 1213,
    1417, 1618, 1721, 1818) must land in result.future_leases, NOT
    result.units.
    """
    future_unit_numbers = [
        "0614", "0711", "0907", "1010", "1113",
        "1213", "1417", "1618", "1721", "1818",
    ]
    # 2 current units, then banner, then 10 future pre-leases.
    units = [
        {"unit_number": "101", "unit_type": "A1", "sqft": 800,
         "resident_name": "Tenant One", "status": "Current",
         "market_rent": 2500, "in_place_rent": 2400},
        {"unit_number": "102", "unit_type": "A1", "sqft": 800,
         "resident_name": "Tenant Two", "status": "Current",
         "market_rent": 2500, "in_place_rent": 2400},
        {"unit_number": "Future Residents/Applicants",
         "unit_type": None, "sqft": None, "resident_name": None,
         "status": None, "market_rent": None, "in_place_rent": 0,
         "charge_details": {}},
    ]
    for un in future_unit_numbers:
        units.append({
            "unit_number": un, "unit_type": "A1", "sqft": 900,
            "resident_name": f"Incoming {un}", "status": None,
            "market_rent": 2700, "in_place_rent": 0,
            "lease_start": datetime(2026, 6, 1),
            "lease_end": datetime(2027, 6, 1),
        })

    result = normalize_units(units, {"unit_number": "Unit"})

    assert len(result.units) == 2
    assert [u["unit_number"] for u in result.units] == ["101", "102"]
    assert len(result.future_leases) == 10
    captured = [fl.unit_number for fl in result.future_leases]
    assert captured == future_unit_numbers


def test_summary_groups_multi_row_header_parsed():
    """Regression for Sixty 11th Bug 2: RealPage wraps '# Of Units'
    across two rows — 'Summary Groups' row has '# Of' at column K and
    the next row has 'Units' at column K. The parser must concatenate
    them to match the label."""
    from openpyxl import Workbook
    from app.services.excel_extraction_service import _parse_realpage_summary_groups

    wb = Workbook()
    ws = wb.active
    # Header row 1: 'Summary Groups' in col A, partial labels elsewhere.
    ws.append([
        "Summary Groups", None, None, None, None,
        "Square", "Market", "Lease", "Security", "Other",
        "# Of", "% Unit", "% Sqft", "Balance",
    ])
    # Header row 2: continuation labels at the same columns.
    ws.append([
        None, None, None, None, None,
        "Footage", "Rent", "Charges", "Deposit", "Deposits",
        "Units", "Occupancy", "Occupied", None,
    ])
    # Data rows (mirrors the Sixty 11th Summary Groups block).
    ws.append([
        "Current/Notice/Vacant Residents", None, None, None, None,
        303721, 863176, 819968.50, None, None, 320, 95.62, 95.00, None,
    ])
    ws.append([
        "Future Residents/Applicants", None, None, None, None,
        9243, 26422, 0.00, None, None, 10, None, None, None,
    ])
    ws.append([
        "Occupied Units", None, None, None, None,
        288796, 821104, None, None, None, 306, 95.62, None, None,
    ])
    ws.append([
        "Total Non Rev Units", None, None, None, None,
        1921, 5662, None, None, None, 2, None, None, None,
    ])
    ws.append([
        "Total Vacant Units", None, None, None, None,
        13004, 36410, None, None, None, 12, None, None, None,
    ])
    ws.append([
        "Totals:", None, None, None, None,
        303721, 863176, 819968.50, None, None, 320, 100.00, 100.00, None,
    ])

    summary = _parse_realpage_summary_groups(ws)
    assert summary is not None, "multi-row header should now parse"
    assert summary["total_units"] == 320
    assert summary["occupied_units"] == 306
    assert summary["vacant_units"] == 12
    assert summary["non_rev_units"] == 2
    assert summary["future_leases"] == 10
    assert summary["total_sqft"] == 303721
    assert summary["total_market_rent"] == 863176
    assert abs(summary["physical_occupancy_pct"] - 95.62) < 0.01
