"""Tests for rent_roll_normalizer.

Covers the eight assertions from the task spec:
  1. "Current/Notice/Vacant Residents" banner row is filtered as junk
     with a reason.
  2. Total/Subtotal rows are filtered.
  3. All real units parse when fed a clean table.
  4. Header detection finds the correct row even when preceded by 5+
     metadata rows.
  5. Column aliasing works — `"Apt #"` instead of `"Unit"` still maps.
  6. VARCHAR overflow doesn't crash — truncated with a warning.
  7. Unmapped columns appear in `unmapped_columns`, not silently dropped.
  8. Missing/malformed dates coerce to None, don't crash.
  9. Currency with `$`, `,`, `()` parses correctly.
"""
from datetime import datetime

import pytest

from app.services.extraction.rent_roll_normalizer import (
    COLUMN_MAX_LENGTHS,
    NormalizationResult,
    coerce_currency,
    coerce_date,
    derive_is_occupied,
    detect_header_row,
    is_junk_row,
    normalize_rows,
    normalize_units,
)


# ─── Synthetic fixtures ──────────────────────────────────────────────────────

REALPAGE_METADATA_ROWS = [
    ["Rent Roll with Lease Charges", "", "", "", "", "", ""],
    ["Talisman Golden Sutherland", "", "", "", "", "", ""],
    ["As of: 04/14/2026", "", "", "", "", "", ""],
    ["", "", "", "", "", "", ""],
    ["Report generated by: Manager", "", "", "", "", "", ""],
]

REALPAGE_HEADER = [
    "Unit", "Floor Plan", "SqFt", "Resident", "Status",
    "Market Rent", "Lease Rent", "Move In", "Lease End",
]


def realpage_table(units: list[list]) -> list[list]:
    """Return a full RealPage-shaped table: 5 metadata rows, then header, then units."""
    return [*REALPAGE_METADATA_ROWS, REALPAGE_HEADER, *units]


# ─── 1. Banner-row filtering ─────────────────────────────────────────────────

def test_current_notice_vacant_banner_is_junk():
    banner = {
        "unit_number": "Current/Notice/Vacant Residents",
        "resident_name": None,
        "market_rent": None,
        "in_place_rent": None,
    }
    junk, reason = is_junk_row(banner)
    assert junk is True
    assert "section header" in reason
    assert "current/notice/vacant" in reason.lower()


def test_banner_row_kept_out_of_units_list_with_reason():
    table = realpage_table([
        ["Current/Notice/Vacant Residents", "", "", "", "", "", "", "", ""],
        ["101", "A1", 800, "Jane Doe", "Occupied", 1200, 1150, "2025-01-01", "2026-01-01"],
    ])
    result = normalize_rows(table)
    assert result.header_row_index == 5
    assert len(result.units) == 1
    assert result.units[0]["unit_number"] == "101"
    assert len(result.skipped_rows) == 1
    assert "section header" in result.skipped_rows[0]["reason"]


# ─── 2. Total / subtotal rows ───────────────────────────────────────────────

def test_total_and_subtotal_rows_are_filtered():
    table = realpage_table([
        ["101", "A1", 800, "Jane", "Occupied", 1200, 1150, "2025-01-01", "2026-01-01"],
        ["Subtotal", "", "", "", "", 1200, 1150, "", ""],
        ["102", "A1", 800, "John", "Occupied", 1200, 1170, "2025-02-01", "2026-02-01"],
        ["Total", "", "", "", "", 2400, 2320, "", ""],
    ])
    result = normalize_rows(table)
    assert len(result.units) == 2
    reasons = [r["reason"] for r in result.skipped_rows]
    assert any("section header" in r for r in reasons)
    assert sum("subtotal" in r.lower() or "total" in r.lower() for r in reasons) >= 2


# ─── 3. Clean table: everything parses ──────────────────────────────────────

def test_clean_table_all_units_parse():
    table = realpage_table([
        ["101", "A1", 800, "Jane", "Occupied", 1200, 1150, "2025-01-01", "2026-01-01"],
        ["102", "A1", 800, "John", "Occupied", 1200, 1170, "2025-02-01", "2026-02-01"],
        ["103", "A2", 900, None, "Vacant", 1300, None, None, None],
    ])
    result = normalize_rows(table)
    assert result.error is None
    assert len(result.units) == 3
    assert result.units[0]["unit_number"] == "101"
    assert result.units[0]["sqft"] == 800
    assert result.units[0]["market_rent"] == 1200
    assert result.units[0]["in_place_rent"] == 1150
    assert result.units[0]["is_occupied"] is True
    assert result.units[2]["is_occupied"] is False
    assert result.units[2]["resident_name"] is None


# ─── 4. Header detection under metadata rows ────────────────────────────────

def test_header_detection_skips_metadata_rows():
    table = realpage_table([
        ["101", "A1", 800, "Jane", "Occupied", 1200, 1150, "2025-01-01", "2026-01-01"],
    ])
    result = normalize_rows(table)
    assert result.header_row_index == 5
    assert len(result.units) == 1


def test_header_detection_returns_minus_one_when_no_candidate():
    table = [
        ["Foo", "Bar", "Baz"],
        ["1", "2", "3"],
        ["4", "5", "6"],
    ]
    idx = detect_header_row(table)
    assert idx == -1


def test_normalize_returns_clear_error_when_header_not_detected():
    table = [["Foo", "Bar"], ["1", "2"]]
    result = normalize_rows(table)
    assert result.header_row_index == -1
    assert result.error is not None
    assert "header" in result.error.lower()
    assert result.units == []


# ─── 5. Column aliasing (Apt # instead of Unit) ──────────────────────────────

def test_apt_hash_alias_maps_to_unit_number():
    table = [
        ["Yardi Export", "", "", "", "", "", ""],
        ["", "", "", "", "", "", ""],
        ["Apt #", "Unit Type", "Size", "Resident Name", "Lease Status",
         "Market Rent", "Actual Rent"],
        ["A-101", "2BR", 1100, "Alice", "Occupied", 1800, 1750],
        ["A-102", "2BR", 1100, "Bob", "Occupied", 1800, 1780],
    ]
    result = normalize_rows(table)
    assert result.error is None
    assert result.column_mapping.get("unit_number") == "Apt #"
    assert result.column_mapping.get("unit_type") == "Unit Type"
    assert result.column_mapping.get("market_rent") == "Market Rent"
    assert len(result.units) == 2


# ─── 6. Truncation doesn't crash (surfaces warning) ──────────────────────────

def test_oversize_strings_truncated_with_warning():
    long_unit = "X" * 120  # > 50
    long_plan = "P" * 80   # > 50
    long_name = "N" * 300  # > 255
    table = realpage_table([
        [long_unit, long_plan, 800, long_name, "Occupied", 1200, 1150,
         "2025-01-01", "2026-01-01"],
    ])
    result = normalize_rows(table)
    assert len(result.units) == 1
    assert len(result.units[0]["unit_number"]) == COLUMN_MAX_LENGTHS["unit_number"]
    assert len(result.units[0]["unit_type"]) == COLUMN_MAX_LENGTHS["unit_type"]
    assert len(result.units[0]["resident_name"]) == COLUMN_MAX_LENGTHS["resident_name"]
    assert any("truncated" in w for w in result.warnings)


# ─── 7. Unmapped columns surfaced ────────────────────────────────────────────

def test_unknown_columns_land_in_unmapped_list():
    table = [
        ["Unit", "Sq Ft", "Resident", "Market Rent", "Lease Rent",
         "Lease Start", "Lease End", "Some Weird PMS Column", "Concessions"],
        ["101", 800, "Jane", 1200, 1150, "2025-01-01", "2026-01-01", "foo", 50],
    ]
    result = normalize_rows(table)
    assert "Some Weird PMS Column" in result.unmapped_columns
    assert "Concessions" in result.unmapped_columns
    assert result.column_mapping.get("unit_number") == "Unit"


# ─── 8. Date coercion is defensive ───────────────────────────────────────────

@pytest.mark.parametrize("bad_value", ["", "N/A", "not a date", None, "  "])
def test_malformed_dates_coerce_to_none(bad_value):
    assert coerce_date(bad_value) is None


def test_excel_serial_date_parses():
    # 45000 ≈ 2023-03-15 in Excel's 1900-epoch serial.
    parsed = coerce_date(45000)
    assert parsed is not None
    assert 2023 <= parsed.year <= 2024


@pytest.mark.parametrize("fmt_value,expected", [
    ("2025-01-15", datetime(2025, 1, 15)),
    ("01/15/2025", datetime(2025, 1, 15)),
    ("1/5/25", datetime(2025, 1, 5)),
])
def test_common_date_formats_parse(fmt_value, expected):
    assert coerce_date(fmt_value) == expected


def test_malformed_date_in_row_does_not_crash_pipeline():
    table = realpage_table([
        ["101", "A1", 800, "Jane", "Occupied", 1200, 1150, "not a date", "garbage"],
    ])
    result = normalize_rows(table)
    assert len(result.units) == 1
    assert result.units[0]["lease_start"] is None
    assert result.units[0]["lease_end"] is None


# ─── 9. Currency coercion ────────────────────────────────────────────────────

@pytest.mark.parametrize("raw,expected", [
    ("$1,200.00", 1200.00),
    ("1,200", 1200.0),
    ("($50.00)", -50.0),
    ("1200", 1200.0),
    (1200, 1200.0),
    (1200.5, 1200.5),
    ("", None),
    ("-", None),
    ("N/A", None),
    ("  $  2,345.67 ", 2345.67),
])
def test_currency_parsing(raw, expected):
    result = coerce_currency(raw)
    if expected is None:
        assert result is None
    else:
        assert result == pytest.approx(expected)


# ─── Occupancy derivation ────────────────────────────────────────────────────

@pytest.mark.parametrize("status,expected", [
    ("Occupied", True),
    ("Occupied No Notice", True),
    ("Current", True),
    ("Notice", True),
    ("Vacant", False),
    ("Vacant Unrented Ready", False),
    ("Model", False),
    ("Down", False),
    ("Admin", False),
    ("", None),
    (None, None),
    ("Something Weird", None),
])
def test_derive_is_occupied(status, expected):
    assert derive_is_occupied(status) is expected


# ─── normalize_units (legacy wrapper) ────────────────────────────────────────

def test_normalize_units_filters_banner_row_from_legacy_extractor_output():
    # The legacy openpyxl parser returns a list of pre-mapped dicts. Verify
    # that the "Current/Notice/Vacant Residents" banner is still filtered.
    units = [
        {"unit_number": "Current/Notice/Vacant Residents",
         "resident_name": None, "market_rent": None, "in_place_rent": None},
        {"unit_number": "101", "unit_type": "A1", "sqft": 800,
         "resident_name": "Jane Doe", "status": "Occupied",
         "market_rent": 1200, "in_place_rent": 1150,
         "lease_start": "2025-01-01", "lease_end": "2026-01-01"},
        {"unit_number": "Total", "resident_name": None,
         "market_rent": 1200, "in_place_rent": 1150},
    ]
    result = normalize_units(units, {"unit_number": "Unit"})
    assert len(result.units) == 1
    assert result.units[0]["unit_number"] == "101"
    assert len(result.skipped_rows) == 2


def test_normalize_units_truncates_oversize_unit_number():
    """Regression: the production StringDataRightTruncation error came from
    shoving 'Current/Notice/Vacant Residents' (30 chars) into VARCHAR(20).
    After the migration -> VARCHAR(50), a short banner like this still gets
    filtered as junk. But if someone constructs a real unit_number > 50,
    we truncate-with-warning rather than crash.
    """
    units = [
        {"unit_number": "A" * 120, "unit_type": "B2",
         "resident_name": "Jane Doe", "status": "Occupied",
         "market_rent": 1500, "in_place_rent": 1450},
    ]
    result = normalize_units(units)
    assert len(result.units) == 1
    assert len(result.units[0]["unit_number"]) == 50
    assert any("truncated" in w for w in result.warnings)


# ─── Sanity: NormalizationResult shape ───────────────────────────────────────

def test_normalization_result_defaults():
    r = NormalizationResult()
    assert r.units == []
    assert r.skipped_rows == []
    assert r.unmapped_columns == []
    assert r.column_mapping == {}
    assert r.warnings == []
    assert r.header_row_index == -1
    assert r.total_rows_scanned == 0
    assert r.error is None
